services:
  api:
    build: .
    container_name: ProjectAPI
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  migrate:
    build: .
    container_name: ProjectMigrate
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: ProjectManagerDB
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  test_db:
    container_name: ProjectTestDB
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_TEST_USER} -d ${POSTGRES_TEST_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  redis:
    container_name: ProjectRedis
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "REDISCLI_AUTH=$$REDIS_PASSWORD redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  redis_data:
  postgres_data:
  postgres_test_data:
