"""migrated_data_and_added_unique_ix

Revision ID: 294148730498
Revises: 003dd7e3bbc4
Create Date: 2026-07-09 11:08:17.856376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294148730498'
down_revision: Union[str, Sequence[str], None] = '003dd7e3bbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE user_project_relation
        SET user_role = 'OWNER'
        WHERE (project_public_id, user_public_id) IN (
            SELECT project_public_id, user_public_id
            FROM (
                SELECT project_public_id, user_public_id,
                       ROW_NUMBER() OVER(PARTITION BY project_public_id ORDER BY user_role ASC) as rn
                FROM user_project_relation
            ) sub
            WHERE rn = 1
        );
    """)

    op.create_index('ix_unique_owner_per_project', 'user_project_relation', ['project_public_id'], unique=True, postgresql_where=sa.text("user_role = 'OWNER'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_owner_per_project', table_name='user_project_relation', postgresql_where=sa.text("user_role = 'OWNER'"))
    op.execute("""
        UPDATE user_project_relation
        SET user_role = 'ADMIN'
        WHERE (project_public_id, user_public_id) IN (
            SELECT project_public_id, user_public_id
            FROM (
                SELECT project_public_id, user_public_id,
                       ROW_NUMBER() OVER(PARTITION BY project_public_id ORDER BY user_role ASC) as rn
                FROM user_project_relation
            ) sub
            WHERE rn = 1
        );
    """)
    # ### end Alembic commands ###
