"""added_projects_model

Revision ID: 514a6b40c629
Revises: 6865b36373f4
Create Date: 2026-06-22 16:42:18.679897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514a6b40c629'
down_revision: Union[str, Sequence[str], None] = '6865b36373f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_public_id', sa.Uuid(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'SUSPENDED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_public_id'),
    sa.UniqueConstraint('project_public_id')
    )
    op.create_unique_constraint(None, 'tasks', ['task_public_id'])
    op.create_unique_constraint(None, 'users', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_table('projects')
    # ### end Alembic commands ###
