"""changed_refresh_tokens_logic

Revision ID: 5d92dce071bd
Revises: a821108542d6
Create Date: 2026-07-01 14:03:59.093170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d92dce071bd'
down_revision: Union[str, Sequence[str], None] = 'a821108542d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_public_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'refresh_tokens', ['token_public_id'])
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'token_id')
    op.drop_column('refresh_tokens', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('refresh_tokens', sa.Column('token_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('refresh_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_column('refresh_tokens', 'token_public_id')
    # ### end Alembic commands ###
