"""added_auth_provider_table

Revision ID: 60f70292f4eb
Revises: b2c4e8f91a03
Create Date: 2026-09-02 15:34:18.799593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f70292f4eb'
down_revision: Union[str, Sequence[str], None] = 'b2c4e8f91a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identity',
    sa.Column('identity_public_id', sa.Uuid(), nullable=False),
    sa.Column('user_public_id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('provider', sa.Enum('LOCAL', 'GOOGLE', 'GITHUB', name='registrationidentity'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_public_id'], ['users.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_public_id'),
    sa.UniqueConstraint('identity_public_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_google_identity'),
    sa.UniqueConstraint('user_public_id', 'provider', name='uq_local_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_identity')
    # ### end Alembic commands ###
