"""migrated_password_and_data_to_new_model

Revision ID: 653b66d311ce
Revises: 60f70292f4eb
Create Date: 2026-09-02 15:38:16.093579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import uuid6
# revision identifiers, used by Alembic.
revision: str = '653b66d311ce'
down_revision: Union[str, Sequence[str], None] = '60f70292f4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT public_id, password FROM users;"))
    identity_data_lst = []
    for user_data in result:
        identity_id = uuid6.uuid7()
        identity_data_lst.append(
            {
                "identity_id":identity_id,
                "user_public_id":user_data.public_id,
                "hashed_password":user_data.password,
                "provider": "LOCAL"
            }
        )
    if identity_data_lst:
        stmt = sa.text("""
        INSERT INTO auth_identity (identity_public_id, user_public_id, hashed_password, provider)
        VALUES (:identity_id, :user_public_id, :hashed_password, :provider);
        """) 
        bind.execute(stmt, identity_data_lst)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("""
    UPDATE users 
    SET password = auth_identity.hashed_password
    FROM auth_identity
    WHERE auth_identity.provider = 'LOCAL' 
    AND users.public_id = auth_identity.user_public_id;
    """)
    # ### end Alembic commands ###
