"""added_token_family_to_refresh

Revision ID: 65a48527555c
Revises: 5d92dce071bd
Create Date: 2026-07-05 11:59:51.517649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a48527555c'
down_revision: Union[str, Sequence[str], None] = '5d92dce071bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('family_id', sa.Uuid(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('is_used', sa.Boolean(), nullable=True))

    op.execute("""
        UPDATE refresh_tokens
        SET expired_at = refresh_tokens.created_at + interval '14 days',
            family_id = gen_random_uuid(),
            is_used = false
        WHERE expired_at IS NULL
    """)

    op.alter_column('refresh_tokens', 'is_used', nullable=False)
    op.alter_column('refresh_tokens', 'family_id', nullable=False)
    op.alter_column('refresh_tokens', 'expired_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'is_used')
    op.drop_column('refresh_tokens', 'family_id')
    op.drop_column('refresh_tokens', 'expired_at')
    # ### end Alembic commands ###
