"""init_user_task

Revision ID: 6865b36373f4
Revises: 
Create Date: 2026-06-22 16:18:23.397479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6865b36373f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_public_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('task_public_id'),
    sa.UniqueConstraint('task_public_id')
    )
    op.create_table('users',
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('public_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('user_public_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_public_id'], ['users.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('user_task_relation',
    sa.Column('user_public_id', sa.Uuid(), nullable=False),
    sa.Column('task_public_id', sa.Uuid(), nullable=False),
    sa.Column('user_role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['task_public_id'], ['tasks.task_public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_public_id'], ['users.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_public_id', 'task_public_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_task_relation')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
