"""added_user_deletes_at_to_user_model

Revision ID: 91f30e587e4b
Revises: f71d98d314ee
Create Date: 2026-08-26 14:12:28.835183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f30e587e4b'
down_revision: Union[str, Sequence[str], None] = 'f71d98d314ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'invitations', ['invitation_public_id'])
    op.add_column('refresh_tokens', sa.Column('session_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deletes_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletes_at')
    op.drop_column('refresh_tokens', 'session_started_at')
   # op.drop_constraint(None, 'invitations', type_='unique')
    # ### end Alembic commands ###
