"""added_user_project_task_relations

Revision ID: a821108542d6
Revises: 514a6b40c629
Create Date: 2026-06-22 17:07:01.995872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a821108542d6'
down_revision: Union[str, Sequence[str], None] = '514a6b40c629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project_relation',
    sa.Column('user_public_id', sa.Uuid(), nullable=False),
    sa.Column('project_public_id', sa.Uuid(), nullable=False),
    sa.Column('user_role', postgresql.ENUM('ADMIN', 'EDITOR', 'VIEWER', name='userrole', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['project_public_id'], ['projects.project_public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_public_id'], ['users.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_public_id', 'project_public_id')
    )
    op.drop_table('user_task_relation')
    op.create_unique_constraint(None, 'projects', ['project_public_id'])
    op.add_column('tasks', sa.Column('project_public_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'projects', ['project_public_id'], ['project_public_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'project_public_id')
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_table('user_task_relation',
    sa.Column('user_public_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_public_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_role', postgresql.ENUM('ADMIN', 'EDITOR', 'VIEWER', name='userrole', create_type=False), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_public_id'], ['tasks.task_public_id'], name=op.f('user_task_relation_task_public_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_public_id'], ['users.public_id'], name=op.f('user_task_relation_user_public_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_public_id', 'task_public_id', name=op.f('user_task_relation_pkey'))
    )
    op.drop_table('user_project_relation')
    # ### end Alembic commands ###
