"""added_invite_model

Revision ID: cca6266c6c33
Revises: 294148730498
Create Date: 2026-07-24 15:48:52.263498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cca6266c6c33'
down_revision: Union[str, Sequence[str], None] = '294148730498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('invitation_public_id', sa.Uuid(), nullable=False),
    sa.Column('project_public_id', sa.Uuid(), nullable=False),
    sa.Column('sender_public_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_public_id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'REVOKED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('user_role', postgresql.ENUM('ADMIN', 'EDITOR', 'VIEWER', 'OWNER', name='userrole', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['project_public_id'], ['projects.project_public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_public_id'], ['users.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_public_id'], ['users.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_public_id'),
    sa.UniqueConstraint('invitation_public_id')
    )
    op.create_index('ix_unique_project_invite', 'invitations', ['project_public_id', 'target_user_public_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_project_invite', table_name='invitations', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('invitations')
    # ### end Alembic commands ###
